export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_RESPONSE = 'SIGN_IN_RESPONSE';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST';
