export const DUMB_ITEMS = [
  {
    id: 0,
    displayLineNumber: 0,
    parent: null,
    vendorPartNo: "CON-SNT-C92048PE",
    manufacturer: "MICROSOFT COMPANY",
    description: "MS321DN LASERPR 38PPM USB TAA LV",
    displayName: "MS321DN LASERPR 38PPM USB TAA LV",
    quantity: 30,
    unitPrice: 0,
    unitPriceFormatted: "0.00",
    totalPrice: 0,
    totalPriceFormatted: "0.00",
    msrp: "MRSP",
    invoice: null,
    discounts: [
      {
        type: "Quote",
        value: 42.00013521974679,
        formattedValue: "42.00",
      },
    ],
    contract: null,
    shortDescription: null,
    mfrNumber: null,
    tdNumber: "000000000013278748",
    upcNumber: null,
    unitListPrice: "0.0",
    unitListPriceFormatted: "0.00",
    extendedPrice: null,
    extendedPriceFormatted: "",
    availability: null,
    rebateValue: null,
    urlProductImage: null,
    urlProductSpecs: null,
    children: [
      {
        id: "0.1",
        displayLineNumber: "100.1",
        parent: 0,
        vendorPartNo: "DUO-MFA-FED-DUO-MFA-FED",
        manufacturer: "MICROSOFT COMPANY",
        description: "Cisco Duo MFA edition for Federal customers",
        displayName: "Cisco Duo MFA edition for Federal customers",
        quantity: 20,
        unitPrice: 36,
        unitPriceFormatted: "36.00",
        totalPrice: null,
        totalPriceFormatted: "",
        msrp: null,
        invoice: null,
        discounts: [],
        contract: {
          id: null,
          status: null,
          duration: null,
          renewedDuration: null,
          startDate: "01-01-0001",
          endDate: "01-01-0001",
          newAgreementStartDate: "01-01-0001",
          newAgreementEndDate: "01-01-0001",
          newUsagePeriodStartDate: "01-01-0001",
          newUsagePeriodEndDate: "01-01-0001",
          supportLevel: null,
          serviceLevel: null,
          usagePeriod: "01-01-0001",
          renewalTerm: 0,
        },
        shortDescription: "Cisco Duo MFA edition for Federal customers",
        mfrNumber: "DUO-MFA-FED-DUO-MFA-FED",
        tdNumber: "13817869",
        upcNumber: null,
        unitListPrice: null,
        unitListPriceFormatted: "36.00",
        extendedPrice: "720.0",
        extendedPriceFormatted: "720.0",
        availability: null,
        rebateValue: null,
        urlProductImage: null,
        urlProductSpecs: null,
        children: null,
        agreements: null,
        ancillaryChargesWithTitles: null,
        annuity: null,
        isSubLine: false,
      },
      {
        id: "0.2",
        displayLineNumber: "100.2",
        parent: 0,
        vendorPartNo: "SVS-DUO-FED-SUP-B",
        manufacturer: "CISCO",
        description: "Cisco Duo Basic Support - Federal",
        displayName: "Cisco Duo MFA edition for Federal customers",
        quantity: 1,
        unitPrice: 0,
        unitPriceFormatted: "0.00",
        totalPrice: null,
        totalPriceFormatted: "",
        msrp: null,
        invoice: null,
        discounts: [],
        contract: {
          id: null,
          status: null,
          duration: null,
          renewedDuration: null,
          startDate: "01-01-0001",
          endDate: "01-01-0001",
          newAgreementStartDate: "01-01-0001",
          newAgreementEndDate: "01-01-0001",
          newUsagePeriodStartDate: "01-01-0001",
          newUsagePeriodEndDate: "01-01-0001",
          supportLevel: null,
          serviceLevel: null,
          usagePeriod: "01-01-0001",
          renewalTerm: 0,
        },
        shortDescription: "Cisco Duo Basic Support - Federal",
        mfrNumber: "SVS-DUO-FED-SUP-B",
        tdNumber: null,
        upcNumber: null,
        unitListPrice: null,
        unitListPriceFormatted: "0.00",
        extendedPrice: "0.0",
        extendedPriceFormatted: "0.0",
        availability: null,
        rebateValue: null,
        urlProductImage: null,
        urlProductSpecs: null,
        children: null,
        agreements: null,
        ancillaryChargesWithTitles: null,
        annuity: null,
        isSubLine: false,
      },
    ],
    agreements: [
      {
        id: "4000608",
        version: "1",
        vendorId: "DD19-447562",
        selectionFlag: "E",
      },
      {
        id: "3058624",
        version: "3",
        vendorId: "DD18-350965",
        selectionFlag: "M",
      },
    ],
    ancillaryChargesWithTitles: null,
    annuity: null,
    isSubLine: false,
    attributes: [
      {
        name: "VENDORQUOTEID",
        value: "4734509146",
      },
      {
        name: "DF_CONFIRMATION_NO",
        value: "1320795298",
      },
      {
        name: "PRICELISTID",
        value: "1109",
      },
      {
        name: "CustomerPoNumber",
        value: "JoseDemoOctober_Deal-B-again",
      },
      {
        name: "VENDOR",
        value: "CISCO",
      },
      {
        name: "DEALIDENTIFIER",
        value: "686450750",
      },
      {
        name: "VENDORQUOTETYPE",
        value: "CCW",
      },
      {
        name: "INTERNAL_COMMENT",
        value: "Can't check UAN with no renewalQuoteId.",
      },
      {
        name: "ShipCompleteType",
        value: "NA",
      },
      {
        name: "TAKEOVER",
        value: "true",
      },
    ],
  },
  {
    id: 1,
    displayLineNumber: 1,
    parent: null,
    vendorPartNo: "CON-SNT-C92048PE",
    manufacturer: "MICROSOFT COMPANY",
    description: "MS321DN LASERPR 38PPM USB TAA LV",
    displayName: "MS321DN LASERPR 38PPM USB TAA LV",
    quantity: 31,
    unitPrice: 1,
    unitPriceFormatted: "0.00",
    totalPrice: 0,
    totalPriceFormatted: "0.00",
    msrp: "MRSP",
    invoice: null,
    discounts: [
      {
        type: "Quote",
        value: 42.00013521974679,
        formattedValue: "42.00",
      },
    ],
    contract: null,
    shortDescription: null,
    mfrNumber: null,
    tdNumber: "000000000013278748",
    upcNumber: null,
    unitListPrice: "0.0",
    unitListPriceFormatted: "0.00",
    extendedPrice: null,
    extendedPriceFormatted: "",
    availability: null,
    rebateValue: null,
    urlProductImage: "http://cdn.cnetcontent.com/ps/TDUS/130x80/80000404.png",
    urlProductSpecs: null,
    children: [
      {
        id: "1.1",
        displayLineNumber: "100.1",
        parent: 1,
        vendorPartNo: "DUO-MFA-FED-DUO-MFA-FED",
        manufacturer: "MICROSOFT COMPANY",
        description: "Cisco Duo MFA edition for Federal customers",
        displayName: "Cisco Duo MFA edition for Federal customers",
        quantity: 21,
        unitPrice: 36,
        unitPriceFormatted: "36.00",
        totalPrice: null,
        totalPriceFormatted: "",
        msrp: null,
        invoice: null,
        discounts: [],
        contract: {
          id: null,
          status: null,
          duration: null,
          renewedDuration: null,
          startDate: "01-01-0001",
          endDate: "01-01-0001",
          newAgreementStartDate: "01-01-0001",
          newAgreementEndDate: "01-01-0001",
          newUsagePeriodStartDate: "01-01-0001",
          newUsagePeriodEndDate: "01-01-0001",
          supportLevel: null,
          serviceLevel: null,
          usagePeriod: "01-01-0001",
          renewalTerm: 0,
        },
        shortDescription: "Cisco Duo MFA edition for Federal customers",
        mfrNumber: "DUO-MFA-FED-DUO-MFA-FED",
        tdNumber: "13817869",
        upcNumber: null,
        unitListPrice: null,
        unitListPriceFormatted: "36.00",
        extendedPrice: "720.0",
        extendedPriceFormatted: "720.0",
        availability: null,
        rebateValue: null,
        urlProductImage:
          "http://cdn.cnetcontent.com/ps/TDUS/130x80/80000404.png",
        urlProductSpecs: null,
        children: null,
        agreements: null,
        ancillaryChargesWithTitles: null,
        annuity: null,
        isSubLine: false,
      },
      {
        id: "1.2",
        displayLineNumber: "100.2",
        parent: 1,
        vendorPartNo: "SVS-DUO-FED-SUP-B",
        manufacturer: "CISCO",
        description: "Cisco Duo Basic Support - Federal",
        displayName: "Cisco Duo MFA edition for Federal customers",
        quantity: 1,
        unitPrice: 0,
        unitPriceFormatted: "0.00",
        totalPrice: null,
        totalPriceFormatted: "",
        msrp: null,
        invoice: null,
        discounts: [],
        contract: {
          id: null,
          status: null,
          duration: null,
          renewedDuration: null,
          startDate: "01-01-0001",
          endDate: "01-01-0001",
          newAgreementStartDate: "01-01-0001",
          newAgreementEndDate: "01-01-0001",
          newUsagePeriodStartDate: "01-01-0001",
          newUsagePeriodEndDate: "01-01-0001",
          supportLevel: null,
          serviceLevel: null,
          usagePeriod: "01-01-0001",
          renewalTerm: 0,
        },
        shortDescription: "Cisco Duo Basic Support - Federal",
        mfrNumber: "SVS-DUO-FED-SUP-B",
        tdNumber: null,
        upcNumber: null,
        unitListPrice: null,
        unitListPriceFormatted: "0.00",
        extendedPrice: "0.0",
        extendedPriceFormatted: "0.0",
        availability: null,
        rebateValue: null,
        urlProductImage: null,
        urlProductSpecs: null,
        children: null,
        agreements: null,
        ancillaryChargesWithTitles: null,
        annuity: null,
        isSubLine: false,
      },
    ],
    agreements: [
      {
        id: "4000608",
        version: "1",
        vendorId: "DD19-447562",
        selectionFlag: "E",
      },
      {
        id: "3058624",
        version: "3",
        vendorId: "DD18-350965",
        selectionFlag: "M",
      },
    ],
    ancillaryChargesWithTitles: null,
    annuity: {
      isAnnuity: true,
      autoRenewal: true,
      startDate: "11/01/2021",
      endDate: "10/31/2022",
      duration: 12,
      billingFrequency: "Annual",
    },
    isSubLine: false,
    attributes: [
      {
        name: "VENDORQUOTEID",
        value: "4734509146",
      },
      {
        name: "DF_CONFIRMATION_NO",
        value: "1320795298",
      },
      {
        name: "PRICELISTID",
        value: "1109",
      },
      {
        name: "CustomerPoNumber",
        value: "JoseDemoOctober_Deal-B-again",
      },
      {
        name: "VENDOR",
        value: "CISCO",
      },
      {
        name: "DEALIDENTIFIER",
        value: "686450750",
      },
      {
        name: "VENDORQUOTETYPE",
        value: "CCW",
      },
      {
        name: "INTERNAL_COMMENT",
        value: "Can't check UAN with no renewalQuoteId.",
      },
      {
        name: "ShipCompleteType",
        value: "NA",
      },
      {
        name: "TAKEOVER",
        value: "true",
      },
    ],
  },
  {
    id: 2,
    displayLineNumber: 2,
    parent: null,
    vendorPartNo: "CON-SNT-C92048PE",
    manufacturer: "MICROSOFT COMPANY",
    description: "MS321DN LASERPR 38PPM USB TAA LV",
    displayName: "MS321DN LASERPR 38PPM USB TAA LV",
    quantity: 32,
    unitPrice: 2,
    unitPriceFormatted: "0.00",
    totalPrice: 0,
    totalPriceFormatted: "0.00",
    msrp: "MRSP",
    invoice: null,
    discounts: [
      {
        type: "Quote",
        value: 42.00013521974679,
        formattedValue: "42.00",
      },
    ],
    contract: null,
    shortDescription: null,
    mfrNumber: null,
    tdNumber: "000000000013278748",
    upcNumber: null,
    unitListPrice: "0.0",
    unitListPriceFormatted: "0.00",
    extendedPrice: null,
    extendedPriceFormatted: "",
    availability: null,
    rebateValue: null,
    urlProductImage: null,
    urlProductSpecs: null,
    children: [
      {
        id: "2.1",
        displayLineNumber: "100.1",
        parent: 2,
        vendorPartNo: "DUO-MFA-FED-DUO-MFA-FED",
        manufacturer: "MICROSOFT COMPANY",
        description: "Cisco Duo MFA edition for Federal customers",
        displayName: "Cisco Duo MFA edition for Federal customers",
        quantity: 22,
        unitPrice: 36,
        unitPriceFormatted: "36.00",
        totalPrice: null,
        totalPriceFormatted: "",
        msrp: null,
        invoice: null,
        discounts: [],
        contract: {
          id: null,
          status: null,
          duration: null,
          renewedDuration: null,
          startDate: "01-01-0001",
          endDate: "01-01-0001",
          newAgreementStartDate: "01-01-0001",
          newAgreementEndDate: "01-01-0001",
          newUsagePeriodStartDate: "01-01-0001",
          newUsagePeriodEndDate: "01-01-0001",
          supportLevel: null,
          serviceLevel: null,
          usagePeriod: "01-01-0001",
          renewalTerm: 0,
        },
        shortDescription: "Cisco Duo MFA edition for Federal customers",
        mfrNumber: "DUO-MFA-FED-DUO-MFA-FED",
        tdNumber: "13817869",
        upcNumber: null,
        unitListPrice: null,
        unitListPriceFormatted: "36.00",
        extendedPrice: "720.0",
        extendedPriceFormatted: "720.0",
        availability: null,
        rebateValue: null,
        urlProductImage: null,
        urlProductSpecs: null,
        children: null,
        agreements: null,
        ancillaryChargesWithTitles: null,
        annuity: null,
        isSubLine: false,
      },
      {
        id: "2.2",
        displayLineNumber: "100.2",
        parent: 2,
        vendorPartNo: "SVS-DUO-FED-SUP-B",
        manufacturer: "CISCO",
        description: "Cisco Duo Basic Support - Federal",
        displayName: "Cisco Duo MFA edition for Federal customers",
        quantity: 1,
        unitPrice: 0,
        unitPriceFormatted: "0.00",
        totalPrice: null,
        totalPriceFormatted: "",
        msrp: null,
        invoice: null,
        discounts: [],
        contract: {
          id: null,
          status: null,
          duration: null,
          renewedDuration: null,
          startDate: "01-01-0001",
          endDate: "01-01-0001",
          newAgreementStartDate: "01-01-0001",
          newAgreementEndDate: "01-01-0001",
          newUsagePeriodStartDate: "01-01-0001",
          newUsagePeriodEndDate: "01-01-0001",
          supportLevel: null,
          serviceLevel: null,
          usagePeriod: "01-01-0001",
          renewalTerm: 0,
        },
        shortDescription: "Cisco Duo Basic Support - Federal",
        mfrNumber: "SVS-DUO-FED-SUP-B",
        tdNumber: null,
        upcNumber: null,
        unitListPrice: null,
        unitListPriceFormatted: "0.00",
        extendedPrice: "0.0",
        extendedPriceFormatted: "0.0",
        availability: null,
        rebateValue: null,
        urlProductImage: null,
        urlProductSpecs: null,
        children: null,
        agreements: null,
        ancillaryChargesWithTitles: null,
        annuity: null,
        isSubLine: false,
      },
    ],
    agreements: [
      {
        id: "4000608",
        version: "1",
        vendorId: "DD19-447562",
        selectionFlag: "E",
      },
      {
        id: "3058624",
        version: "3",
        vendorId: "DD18-350965",
        selectionFlag: "M",
      },
    ],
    ancillaryChargesWithTitles: null,
    annuity: null,
    isSubLine: false,
    attributes: [
      {
        name: "VENDORQUOTEID",
        value: "4734509146",
      },
      {
        name: "DF_CONFIRMATION_NO",
        value: "1320795298",
      },
      {
        name: "PRICELISTID",
        value: "1109",
      },
      {
        name: "CustomerPoNumber",
        value: "JoseDemoOctober_Deal-B-again",
      },
      {
        name: "VENDOR",
        value: "CISCO",
      },
      {
        name: "DEALIDENTIFIER",
        value: "686450750",
      },
      {
        name: "VENDORQUOTETYPE",
        value: "CCW",
      },
      {
        name: "INTERNAL_COMMENT",
        value: "Can't check UAN with no renewalQuoteId.",
      },
      {
        name: "ShipCompleteType",
        value: "NA",
      },
      {
        name: "TAKEOVER",
        value: "true",
      },
    ],
  },
  {
    id: 3,
    displayLineNumber: 3,
    parent: null,
    vendorPartNo: "CON-SNT-C92048PE",
    manufacturer: "MICROSOFT COMPANY",
    description: "MS321DN LASERPR 38PPM USB TAA LV",
    displayName: "MS321DN LASERPR 38PPM USB TAA LV",
    quantity: 33,
    unitPrice: 3,
    unitPriceFormatted: "0.00",
    totalPrice: 0,
    totalPriceFormatted: "0.00",
    msrp: "MRSP",
    invoice: null,
    discounts: [
      {
        type: "Quote",
        value: 42.00013521974679,
        formattedValue: "42.00",
      },
    ],
    contract: null,
    shortDescription: null,
    mfrNumber: null,
    tdNumber: "000000000013278748",
    upcNumber: null,
    unitListPrice: "0.0",
    unitListPriceFormatted: "0.00",
    extendedPrice: null,
    extendedPriceFormatted: "",
    availability: null,
    rebateValue: null,
    urlProductImage: "http://cdn.cnetcontent.com/ps/TDUS/130x80/80000404.png",
    urlProductSpecs: null,
    children: [
      {
        id: "3.1",
        displayLineNumber: "100.1",
        parent: 3,
        vendorPartNo: "DUO-MFA-FED-DUO-MFA-FED",
        manufacturer: "MICROSOFT COMPANY",
        description: "Cisco Duo MFA edition for Federal customers",
        displayName: "Cisco Duo MFA edition for Federal customers",
        quantity: 23,
        unitPrice: 36,
        unitPriceFormatted: "36.00",
        totalPrice: null,
        totalPriceFormatted: "",
        msrp: null,
        invoice: null,
        discounts: [],
        contract: {
          id: null,
          status: null,
          duration: null,
          renewedDuration: null,
          startDate: "01-01-0001",
          endDate: "01-01-0001",
          newAgreementStartDate: "01-01-0001",
          newAgreementEndDate: "01-01-0001",
          newUsagePeriodStartDate: "01-01-0001",
          newUsagePeriodEndDate: "01-01-0001",
          supportLevel: null,
          serviceLevel: null,
          usagePeriod: "01-01-0001",
          renewalTerm: 0,
        },
        shortDescription: "Cisco Duo MFA edition for Federal customers",
        mfrNumber: "DUO-MFA-FED-DUO-MFA-FED",
        tdNumber: "13817869",
        upcNumber: null,
        unitListPrice: null,
        unitListPriceFormatted: "36.00",
        extendedPrice: "720.0",
        extendedPriceFormatted: "720.0",
        availability: null,
        rebateValue: null,
        urlProductImage:
          "http://cdn.cnetcontent.com/ps/TDUS/130x80/80000404.png",
        urlProductSpecs: null,
        children: null,
        agreements: null,
        ancillaryChargesWithTitles: null,
        annuity: null,
        isSubLine: false,
      },
      {
        id: "3.2",
        displayLineNumber: "100.2",
        parent: 3,
        vendorPartNo: "SVS-DUO-FED-SUP-B",
        manufacturer: "CISCO",
        description: "Cisco Duo Basic Support - Federal",
        displayName: "Cisco Duo MFA edition for Federal customers",
        quantity: 1,
        unitPrice: 0,
        unitPriceFormatted: "0.00",
        totalPrice: null,
        totalPriceFormatted: "",
        msrp: null,
        invoice: null,
        discounts: [],
        contract: {
          id: null,
          status: null,
          duration: null,
          renewedDuration: null,
          startDate: "01-01-0001",
          endDate: "01-01-0001",
          newAgreementStartDate: "01-01-0001",
          newAgreementEndDate: "01-01-0001",
          newUsagePeriodStartDate: "01-01-0001",
          newUsagePeriodEndDate: "01-01-0001",
          supportLevel: null,
          serviceLevel: null,
          usagePeriod: "01-01-0001",
          renewalTerm: 0,
        },
        shortDescription: "Cisco Duo Basic Support - Federal",
        mfrNumber: "SVS-DUO-FED-SUP-B",
        tdNumber: null,
        upcNumber: null,
        unitListPrice: null,
        unitListPriceFormatted: "0.00",
        extendedPrice: "0.0",
        extendedPriceFormatted: "0.0",
        availability: null,
        rebateValue: null,
        urlProductImage: null,
        urlProductSpecs: null,
        children: null,
        agreements: null,
        ancillaryChargesWithTitles: null,
        annuity: null,
        isSubLine: false,
      },
    ],
    agreements: [
      {
        id: "4000608",
        version: "1",
        vendorId: "DD19-447562",
        selectionFlag: "E",
      },
      {
        id: "3058624",
        version: "3",
        vendorId: "DD18-350965",
        selectionFlag: "M",
      },
    ],
    ancillaryChargesWithTitles: null,
    annuity: {
      isAnnuity: true,
      autoRenewal: true,
      startDate: "11/01/2021",
      endDate: "10/31/2022",
      duration: 12,
      billingFrequency: "Annual",
    },
    isSubLine: false,
    attributes: [
      {
        name: "VENDORQUOTEID",
        value: "4734509146",
      },
      {
        name: "DF_CONFIRMATION_NO",
        value: "1320795298",
      },
      {
        name: "PRICELISTID",
        value: "1109",
      },
      {
        name: "CustomerPoNumber",
        value: "JoseDemoOctober_Deal-B-again",
      },
      {
        name: "VENDOR",
        value: "CISCO",
      },
      {
        name: "DEALIDENTIFIER",
        value: "686450750",
      },
      {
        name: "VENDORQUOTETYPE",
        value: "CCW",
      },
      {
        name: "INTERNAL_COMMENT",
        value: "Can't check UAN with no renewalQuoteId.",
      },
      {
        name: "ShipCompleteType",
        value: "NA",
      },
      {
        name: "TAKEOVER",
        value: "true",
      },
    ],
  },
  {
    id: 4,
    displayLineNumber: 4,
    parent: null,
    vendorPartNo: "CON-SNT-C92048PE",
    manufacturer: "MICROSOFT COMPANY",
    description: "MS321DN LASERPR 38PPM USB TAA LV",
    displayName: "MS321DN LASERPR 38PPM USB TAA LV",
    quantity: 34,
    unitPrice: 4,
    unitPriceFormatted: "0.00",
    totalPrice: 0,
    totalPriceFormatted: "0.00",
    msrp: "MRSP",
    invoice: null,
    discounts: [
      {
        type: "Quote",
        value: 42.00013521974679,
        formattedValue: "42.00",
      },
    ],
    contract: null,
    shortDescription: null,
    mfrNumber: null,
    tdNumber: "000000000013278748",
    upcNumber: null,
    unitListPrice: "0.0",
    unitListPriceFormatted: "0.00",
    extendedPrice: null,
    extendedPriceFormatted: "",
    availability: null,
    rebateValue: null,
    urlProductImage: null,
    urlProductSpecs: null,
    children: [
      {
        id: "4.1",
        displayLineNumber: "100.1",
        parent: 4,
        vendorPartNo: "DUO-MFA-FED-DUO-MFA-FED",
        manufacturer: "MICROSOFT COMPANY",
        description: "Cisco Duo MFA edition for Federal customers",
        displayName: "Cisco Duo MFA edition for Federal customers",
        quantity: 24,
        unitPrice: 36,
        unitPriceFormatted: "36.00",
        totalPrice: null,
        totalPriceFormatted: "",
        msrp: null,
        invoice: null,
        discounts: [],
        contract: {
          id: null,
          status: null,
          duration: null,
          renewedDuration: null,
          startDate: "01-01-0001",
          endDate: "01-01-0001",
          newAgreementStartDate: "01-01-0001",
          newAgreementEndDate: "01-01-0001",
          newUsagePeriodStartDate: "01-01-0001",
          newUsagePeriodEndDate: "01-01-0001",
          supportLevel: null,
          serviceLevel: null,
          usagePeriod: "01-01-0001",
          renewalTerm: 0,
        },
        shortDescription: "Cisco Duo MFA edition for Federal customers",
        mfrNumber: "DUO-MFA-FED-DUO-MFA-FED",
        tdNumber: "13817869",
        upcNumber: null,
        unitListPrice: null,
        unitListPriceFormatted: "36.00",
        extendedPrice: "720.0",
        extendedPriceFormatted: "720.0",
        availability: null,
        rebateValue: null,
        urlProductImage: null,
        urlProductSpecs: null,
        children: null,
        agreements: null,
        ancillaryChargesWithTitles: null,
        annuity: null,
        isSubLine: false,
      },
      {
        id: "4.2",
        displayLineNumber: "100.2",
        parent: 4,
        vendorPartNo: "SVS-DUO-FED-SUP-B",
        manufacturer: "CISCO",
        description: "Cisco Duo Basic Support - Federal",
        displayName: "Cisco Duo MFA edition for Federal customers",
        quantity: 1,
        unitPrice: 0,
        unitPriceFormatted: "0.00",
        totalPrice: null,
        totalPriceFormatted: "",
        msrp: null,
        invoice: null,
        discounts: [],
        contract: {
          id: null,
          status: null,
          duration: null,
          renewedDuration: null,
          startDate: "01-01-0001",
          endDate: "01-01-0001",
          newAgreementStartDate: "01-01-0001",
          newAgreementEndDate: "01-01-0001",
          newUsagePeriodStartDate: "01-01-0001",
          newUsagePeriodEndDate: "01-01-0001",
          supportLevel: null,
          serviceLevel: null,
          usagePeriod: "01-01-0001",
          renewalTerm: 0,
        },
        shortDescription: "Cisco Duo Basic Support - Federal",
        mfrNumber: "SVS-DUO-FED-SUP-B",
        tdNumber: null,
        upcNumber: null,
        unitListPrice: null,
        unitListPriceFormatted: "0.00",
        extendedPrice: "0.0",
        extendedPriceFormatted: "0.0",
        availability: null,
        rebateValue: null,
        urlProductImage: null,
        urlProductSpecs: null,
        children: null,
        agreements: null,
        ancillaryChargesWithTitles: null,
        annuity: null,
        isSubLine: false,
      },
    ],
    agreements: [
      {
        id: "4000608",
        version: "1",
        vendorId: "DD19-447562",
        selectionFlag: "E",
      },
      {
        id: "3058624",
        version: "3",
        vendorId: "DD18-350965",
        selectionFlag: "M",
      },
    ],
    ancillaryChargesWithTitles: null,
    annuity: null,
    isSubLine: false,
    attributes: [
      {
        name: "VENDORQUOTEID",
        value: "4734509146",
      },
      {
        name: "DF_CONFIRMATION_NO",
        value: "1320795298",
      },
      {
        name: "PRICELISTID",
        value: "1109",
      },
      {
        name: "CustomerPoNumber",
        value: "JoseDemoOctober_Deal-B-again",
      },
      {
        name: "VENDOR",
        value: "CISCO",
      },
      {
        name: "DEALIDENTIFIER",
        value: "686450750",
      },
      {
        name: "VENDORQUOTETYPE",
        value: "CCW",
      },
      {
        name: "INTERNAL_COMMENT",
        value: "Can't check UAN with no renewalQuoteId.",
      },
      {
        name: "ShipCompleteType",
        value: "NA",
      },
      {
        name: "TAKEOVER",
        value: "true",
      },
    ],
  },
];
