namespace DigitalCommercePlatform.UIService.Order.Enums
{
    public enum BlockReason { UNDEFINED, ADDRESS_VALIDATION, CREDIT_CARD_HOLD, EXPORT_HOLD, FLOOR_PLANNER_HOLD, MARGIN_HOLD, TAX_BLOCK, DELIVERY_BLOCK, EC_MESSAGE };
}