namespace DigitalCommercePlatform.UIService.Order.Enums
{
    public enum OrderSort
    {
        CREATED,
        CREATEDBY,
        UPDATED,
        ID,
        BLOCKSTATUS,
        BUSINESSORDERLEVEL,
        BUSINESSORDERTYPE,
        CONFIRMATIONSTATUS,
        CONTACTNAME,
        CURRENCY,
        CUSTOMER,
        CUSTOMERNAME,
        CUSTOMERPO,
        DELIVERYSTATUS,
        ENDUSERPO,
        HOLDREASON,
        ORDERID,
        ORDERSTATUS,
        ORDERTYPE,
        PODATE,
        PRICE,
        QUOTEID,
        QUOTEREVISION,
        SALESORG,
        SALESTEAMNAME,
        SHIPTONAME,
        SYSTEM,
        WORKFLOWID,
        VENDORSOLUTIONREPRESENTATIVE,
        VENDORSOLUTIONASSOCIATE
    };
}