const columnDefs = [
  {
    headerName: 'Line №',
    field: 'id',
    width: '100px',
    sortable: false,
    cellStyle: {
      'justify-content': 'flex-end',
      'white-space': 'normal',
      padding: '32px 18px',
    },
    autoHeight: true,
    headerClass: 'right-aligned',
  },
  {
    headerName: 'Description',
    field: 'description',
    sortable: false,
    width: '500px',
    cellStyle: { 'white-space': 'normal', padding: '32px 18px' },
    autoHeight: true,
    headerClass: 'center-aligned',
  },
  {
    headerName: 'Line Status',
    field: 'status',
    sortable: false,
    cellStyle: { 'white-space': 'normal', padding: '32px 18px' },
    autoHeight: true,
  },
  {
    headerName: 'Ship date',
    field: 'shipDate',
    sortable: false,
    cellStyle: { 'justify-content': 'center', padding: '32px 18px' },
    autoHeight: true,
    headerClass: 'center-aligned',
  },
  {
    headerName: 'Unit cost',
    field: 'unitPriceFormatted',
    sortable: false,
    cellStyle: { 'justify-content': 'flex-end', padding: '32px 18px' },
    autoHeight: true,
    headerClass: 'right-aligned',
  },
  {
    headerName: 'Qty',
    field: 'quantity',
    sortable: false,
    cellStyle: { 'justify-content': 'flex-end', padding: '32px 18px' },
    autoHeight: true,
    headerClass: 'right-aligned',
  },
  {
    headerName: 'Line  total',
    field: 'totalPriceFormatted',
    width: '150px',
    sortable: false,
    cellStyle: { 'justify-content': 'flex-end', padding: '32px 18px' },
    autoHeight: true,
    headerClass: 'right-aligned',
  },
  {
    headerName: '',
    field: 'actions',
    width: '50px',
    sortable: false,
    cellStyle: { 'justify-content': 'center', padding: '32px 18px' },
    autoHeight: true,
    headerClass: 'center-aligned',
  },
];

export default columnDefs;
