//2021 (c) Tech Data Corporation -. All Rights Reserved.
// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:DigitalCommercePlatform.UIServices.Browse.Tests.Controllers.DetailControllerTests.GetCustomerDetails(DigitalCommercePlatform.UIServices.Browse.Actions.Abstract.ResponseBase{DigitalCommercePlatform.UIServices.Browse.Actions.GetCustomerDetails.GetCustomerHandler.Response})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:DigitalCommercePlatform.UIServices.Browse.Tests.Controllers.DetailControllerTests.GetProductSummary(DigitalCommercePlatform.UIServices.Browse.Actions.Abstract.ResponseBase{DigitalCommercePlatform.UIServices.Browse.Actions.GetProductDetails.GetProductSummaryHandler.Response})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:DigitalCommercePlatform.UIServices.Browse.Tests.Controllers.DetailControllerTests.GetCatalogDetails(DigitalCommercePlatform.UIServices.Browse.Actions.Abstract.ResponseBase{DigitalCommercePlatform.UIServices.Browse.Actions.GetCatalogDetails.GetCatalogHandler.Response})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:DigitalCommercePlatform.UIServices.Browse.Tests.Controllers.DetailControllerTests.FindProductDetails(DigitalCommercePlatform.UIServices.Browse.Actions.Abstract.ResponseBase{DigitalCommercePlatform.UIServices.Browse.Actions.GetProductSummary.FindProductHandler.Response},DigitalCommercePlatform.UIServices.Browse.Models.Product.Find.FindProductModel)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:DigitalCommercePlatform.UIServices.Browse.Tests.Controllers.DetailControllerTests.FindSummaryDetails(DigitalCommercePlatform.UIServices.Browse.Actions.Abstract.ResponseBase{DigitalCommercePlatform.UIServices.Browse.Actions.GetProductSummary.FindSummaryHandler.Response},DigitalCommercePlatform.UIServices.Browse.Models.Product.Find.FindProductModel)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:DigitalCommercePlatform.UIServices.Browse.Tests.Controllers.DetailControllerTests.GetProductDetails(DigitalCommercePlatform.UIServices.Browse.Actions.Abstract.ResponseBase{DigitalCommercePlatform.UIServices.Browse.Actions.GetProductDetails.GetProductDetailsHandler.Response})~System.Threading.Tasks.Task")]
