// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:DigitalCommercePlatform.UIServices.Browse.Tests.Controllers.BrowseControllerTests.GetCartDetails(DigitalCommercePlatform.UIServices.Browse.Actions.Abstract.ResponseBase{DigitalCommercePlatform.UIServices.Browse.Actions.GetCartDetails.GetCartHandler.GetCartResponse})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:DigitalCommercePlatform.UIServices.Browse.Tests.Controllers.BrowseControllerTests.GetCustomerDetails(DigitalCommercePlatform.UIServices.Browse.Actions.Abstract.ResponseBase{DigitalCommercePlatform.UIServices.Browse.Actions.GetCustomerDetails.GetCustomerHandler.GetCustomerResponse})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:DigitalCommercePlatform.UIServices.Browse.Tests.Controllers.BrowseControllerTests.GetProductSummary(DigitalCommercePlatform.UIServices.Browse.Actions.Abstract.ResponseBase{DigitalCommercePlatform.UIServices.Browse.Actions.GetProductDetails.GetProductSummaryHandler.GetProductSummaryResponse})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:DigitalCommercePlatform.UIServices.Browse.Tests.Controllers.BrowseControllerTests.GetCatalogDetails(DigitalCommercePlatform.UIServices.Browse.Actions.Abstract.ResponseBase{DigitalCommercePlatform.UIServices.Browse.Actions.GetCatalogDetails.GetCatalogHandler.GetCatalogResponse})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:DigitalCommercePlatform.UIServices.Browse.Tests.Controllers.BrowseControllerTests.GetHeaderDetails(DigitalCommercePlatform.UIServices.Browse.Actions.Abstract.ResponseBase{DigitalCommercePlatform.UIServices.Browse.Actions.GetHeaderDetails.GetHeaderHandler.GetHeaderResponse})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:DigitalCommercePlatform.UIServices.Browse.Tests.Controllers.BrowseControllerTests.FindProductDetails(DigitalCommercePlatform.UIServices.Browse.Actions.Abstract.ResponseBase{DigitalCommercePlatform.UIServices.Browse.Actions.GetProductSummary.FindProductHandler.GetProductResponse},DigitalCommercePlatform.UIServices.Browse.Models.Product.Find.FindProductModel)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:DigitalCommercePlatform.UIServices.Browse.Tests.Controllers.BrowseControllerTests.FindSummaryDetails(DigitalCommercePlatform.UIServices.Browse.Actions.Abstract.ResponseBase{DigitalCommercePlatform.UIServices.Browse.Actions.GetProductSummary.FindSummaryHandler.FindSummaryResponse},DigitalCommercePlatform.UIServices.Browse.Models.Product.Find.FindProductModel)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:DigitalCommercePlatform.UIServices.Browse.Tests.Controllers.BrowseControllerTests.GetProductDetails(DigitalCommercePlatform.UIServices.Browse.Actions.Abstract.ResponseBase{DigitalCommercePlatform.UIServices.Browse.Actions.GetProductDetails.GetProductDetailsHandler.GetProductDetailsResponse})~System.Threading.Tasks.Task")]
