module.exports = {
    getRandomDate: function () {
        let [month, date, year] = new Date()
            .toLocaleDateString("en-US")
            .split("/");
        let dayFactor = Math.floor(Math.random() * 7);
        let deltaFactor = Math.floor(Math.random() * 2) ? 1 : -1;
        let randomDate = parseInt(date) + dayFactor * deltaFactor;
        console.log(month, date, year, dayFactor, deltaFactor, randomDate);
        return new Date(year, month, randomDate).toISOString();
    },
    getRandomArrayWithIds: (maxLength) => {
        const arrayLength = Math.floor(Math.random() * (maxLength + 1));
        let ids = [];
        const itemDefinition = {
            id: "123456789",
            version: "1",
            vendorId: "2323232",
            selectionFlag: "flag",
        };
        for (let i = 0; i < arrayLength; i++) {
            ids.push(itemDefinition);
        }
        return ids;
    },
    getRandomValues(range) {
        return String(1.0 * Math.floor(Math.random() * (range + 1)));
    },
    getRandomNumber(maxValue) {
        return Math.floor(Math.random() * maxValue + 1);
    },
    getQuoteDetailsResponse() {
        return {
            "content": {
                "details": {
                    "shipTo": {
                        "id": null,
                        "companyName": "TECH DATA CORPORATION",
                        "name": null,
                        "line1": "5350 Tech Data Dr",
                        "line2": null,
                        "line3": null,
                        "city": "Clearwater",
                        "state": "FL",
                        "zip": null,
                        "postalCode": "33760",
                        "country": "US",
                        "email": null,
                        "phoneNumber": null
                    },
                    "endUser": {
                        "id": null,
                        "companyName": "PEIGENESISCOM123",
                        "name": "Daniel  Vogt",
                        "line1": "2180 HORNIG RD",
                        "line2": null,
                        "line3": null,
                        "city": "PHILADELPHIA",
                        "state": "PA",
                        "zip": null,
                        "postalCode": "19116",
                        "country": "US",
                        "email": "Daniel.Vogt@techdata.com",
                        "phoneNumber": "0000"
                    },
                    "reseller": {
                        "id": null,
                        "companyName": "TECH DATA CORPORATION",
                        "name": "Daniel  Vogt",
                        "line1": "5350 Tech Data Dr",
                        "line2": " ",
                        "line3": null,
                        "city": "Clearwater",
                        "state": "FL",
                        "zip": null,
                        "postalCode": "33760",
                        "country": "US",
                        "email": "Daniel.Vogt@techdata.com",
                        "phoneNumber": "0000"
                    },
                    "source": [],
                    "notes": null,
                    "id": "121764062",
                    "orders": [{"id": null, "system": "Q", "salesOrg": "0100"}],
                    "customerPO": "21",
                    "endUserPO": null,
                    "poDate": null,
                    "quoteReference": "CCW QuoteId:4732840041",
                    "spaId": null,
                    "currency": "USD",
                    "currencySymbol": "$",
                    "subTotal": 19011.5500000,
                    "subTotalFormatted": "19,011.55",
                    "tier": "Commercial",
                    "items": [{
                        "id": "1",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "SAN Bundle incl. Nexus 93180YC-FX&MDS 91",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000014247378",
                        "upcNumber": null,
                        "unitListPrice": "0.0",
                        "unitListPriceFormatted": "0.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "2",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "MDS 9132T 32G 1 RU FC SWCH 8 ACTIVE FC",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000012996740",
                        "upcNumber": null,
                        "unitListPrice": "5820.3000000",
                        "unitListPriceFormatted": "5,820.30",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "3",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "SNTC-8X5XNBD MDS 9132T 32G 1 RU FC SWCH",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000012996739",
                        "upcNumber": null,
                        "unitListPrice": "225.0000000",
                        "unitListPriceFormatted": "225.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "4",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "650W AC PSU PT SIDE EXHAUST",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000013387287",
                        "upcNumber": null,
                        "unitListPrice": "827.8900000",
                        "unitListPriceFormatted": "827.89",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "5",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "MDS 9132 FAN TRAY PT SIDE EXHAUST",
                        "quantity": 2,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000013366560",
                        "upcNumber": null,
                        "unitListPrice": "200.7000000",
                        "unitListPriceFormatted": "200.70",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "6",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "650W AC PSU PT SIDE EXHAUST",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000013387287",
                        "upcNumber": null,
                        "unitListPrice": "827.8900000",
                        "unitListPriceFormatted": "827.89",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "7",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "16GBPS FC S/W SFP+ LC",
                        "quantity": 8,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000011262480",
                        "upcNumber": null,
                        "unitListPrice": "333.1600000",
                        "unitListPriceFormatted": "333.16",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "8",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "CTO PWR CORD 125VAC 13A NEMA 5-15 PLUG N",
                        "quantity": 2,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000010117017",
                        "upcNumber": null,
                        "unitListPrice": "0.0",
                        "unitListPriceFormatted": "0.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "9",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "MDS 9132 FAN TRAY PT SIDE EXHAUST",
                        "quantity": 2,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000013366560",
                        "upcNumber": null,
                        "unitListPrice": "200.7000000",
                        "unitListPriceFormatted": "200.70",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "10",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "MDS 9132T Accessory Kit for Cisco",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000014116891",
                        "upcNumber": null,
                        "unitListPrice": "0.0",
                        "unitListPriceFormatted": "0.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "11",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "Filler card for Blank Expansion Module S",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000014116888",
                        "upcNumber": null,
                        "unitListPrice": "0.0",
                        "unitListPriceFormatted": "0.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "12",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "NEXUS 9300 48P 10/25G SFP+ 6P 100G QSFP",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000012660188",
                        "upcNumber": null,
                        "unitListPrice": "27596.2500000",
                        "unitListPriceFormatted": "27,596.25",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "13",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "SNTC-8X5XNBD NEXUS 9300 W/ 48P",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000012705704",
                        "upcNumber": null,
                        "unitListPrice": "1318.8600000",
                        "unitListPriceFormatted": "1,318.86",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "14",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "Dummy PID for mode selection",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000014118038",
                        "upcNumber": null,
                        "unitListPrice": "0.0",
                        "unitListPriceFormatted": "0.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "15",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "ACI STOR S/W LIC",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000013366143",
                        "upcNumber": null,
                        "unitListPrice": "18063.0000000",
                        "unitListPriceFormatted": "18,063.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "16",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "SWSS UPG ACI STOR S/W LIC",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000013366142",
                        "upcNumber": null,
                        "unitListPrice": "366.0000000",
                        "unitListPriceFormatted": "366.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "17",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "OPT OUT PID FOR ACI ADV Subscription USE",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000014118988",
                        "upcNumber": null,
                        "unitListPrice": "0.0",
                        "unitListPriceFormatted": "0.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "18",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "Nexus 3K/9K Fixed Accessory Kit, 1RU fr",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000013753097",
                        "upcNumber": null,
                        "unitListPrice": "0.0",
                        "unitListPriceFormatted": "0.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "19",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "Nexus NEBs AC 500W PSU - Port Side Inta",
                        "quantity": 2,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000014119303",
                        "upcNumber": null,
                        "unitListPrice": "0.0",
                        "unitListPriceFormatted": "0.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "20",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "CTO PWR CORD 125VAC 13A NEMA 5-15 PLUG N",
                        "quantity": 2,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000010117017",
                        "upcNumber": null,
                        "unitListPrice": "0.0",
                        "unitListPriceFormatted": "0.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }]
                }
            }, "error": {"code": 0, "messages": [], "isError": false}
        };
    },
    getOrderDetailsResponse() {
        const  getRandomNumber = (maxValue) => {
            return Math.floor(Math.random() * maxValue + 1);
        };
        const randomStr = (len, arr) => {
            let ans = '';
            for (let i = len; i > 0; i--) {
                ans +=
                  arr[Math.floor(Math.random() * arr.length)];
            }
            return ans.toUpperCase();
        };
        const abc = '123456789abcdefghijkmnlopqrstvuwxyz'
        const randomDate = (start, end) => {
            return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
        }

        return {
            "content": {
              "shipTo": {
                "id": null,
                "companyName": null,
                "name": "TECH DATA PRODUCT MANAGEMENT INC",
                "line1": "13472 MARLAY AVENUE",
                "line2": null,
                "line3": null,
                "city": "FONTANA",
                "state": "CA",
                "zip": "92337",
                "postalCode": null,
                "country": "US",
                "email": null,
                "contactEmail": null,
                "phoneNumber": null
              },
              "endUser": [],
              "paymentDetails": {
                "netValue": null,
                "reference": "JoseDemoOctober_quote1",
                "currency": "USD",
                "currencySymbol": "$",
                "paymentTermText": null,
                "subtotal": null,
                "tax": 0.0,
                "freight": 0.0,
                "otherFees": 0.0,
                "total": 0.0
              },
              "customer": "TECH DATA PRODUCT MANAGEMENT INC",
              "items": [
                {
                  "id": "100",
                  "parent": null,
                  "vendorPartNo": "C9200-48P-E",
                  "manufacturer": "CISCO",
                  "description1": null,
                  "quantity": 9,
                  "unitPrice": 0.0,
                  "unitPriceFormatted": "0.00",
                  "totalPrice": 0.0,
                  "totalPriceFormatted": "0.00",
                  "msrp": null,
                  "invoice": null,
                  "shipDates": ['10-6-2021', '10-8-2021'],
                  "invoices": [
                    {
                      "id": "8035189627",
                      "line": "1",
                      "quantity": 3,
                      "price": 38.19,
                      "created": "11-18-2021"
                    }
                  ],
                  "trackings": [
                    {
                      "orderNumber": null,
                      "invoiceNumber": null,
                      "id": null,
                      "carrier": "FEDEX",
                      "serviceLevel": "FEDEX GROUND",
                      "trackingNumber": "486179958091",
                      "trackingLink": "http://www.fedex.com/Tracking?&cntry_code=us&language=english&tracknumbers=486179958091",
                      "type": "W0",
                      "description": "FEDX GRND",
                      "date": "10-06-2021",
                      "dNote": "7038822559",
                      "dNoteLineNumber": "10",
                      "goodsReceiptNo": null
                    }
                  ],
                  "discounts": null,
                  "contract": null,
                  "displayName": "Cisco Catalyst 9200 - Essential Edition - switch - 48 ports - smart - rack-mountable",
                  "mfrNumber": "C9200-48P-E",
                  "tdNumber": "13523591",
                  "upcNumber": null,
                  "unitListPrice": null,
                  "unitListPriceFormatted": null,
                  "extendedPrice": null,
                  "extendedPriceFormatted": "",
                  "availability": null,
                  "rebateValue": null,
                  "urlProductImage": "/non-existing-image.png",
                  "urlProductSpecs": null,
                  "children": [
                    {
                      "id": "101",
                      "parent": "100",
                      "vendorPartNo": null,
                      "manufacturer": "HP ENT",
                      "displayName": "HP DL360P GEN8 S-BUY E5-2620 BASE US SVR",
                      "quantity": 6,
                      "unitPrice": 8572.18,
                      "unitPriceFormatted": "8,572.18",
                      "totalPrice": 51433.08,
                      "totalPriceFormatted": "51,433.08",
                      "msrp": null,
                      "invoice": null,
                      "invoices": [
                        {
                          "id": "8035207610",
                          "line": "2",
                          "quantity": 6,
                          "price": 51433.08,
                          "created": "07-16-2021"              }
                      ],
                      "shipDates": ['10-6-2021', '11-9-2021', '02-22-2021'],
                      "trackings": [
                        {
                          "orderNumber": null,
                          "invoiceNumber": null,
                          "id": null,
                          "carrier": "CAMPBELL'S EXPRESS",
                          "serviceLevel": "LTL",
                          "trackingNumber": "7038809671",
                          "trackingLink": "http://expo.expeditors.com/expo/SQGuest?SearchType=shipmentSearch&TrackingNumber=7038809671",
                          "type": "JV",
                          "displayName": "CAMPBELLS EXPESS",
                          "date": "10-06-2021",
                          "dNote": "7038809671",
                          "dNoteLineNumber": "20",
                          "goodsReceiptNo": null              }
                      ],
                      "discounts": null,
                      "contract": null,
                      "displayName": null,
                      "mfrNumber": "670633-S01",
                      "tdNumber": "10214041",
                      "upcNumber": null,
                      "unitListPrice": null,
                      "unitListPriceFormatted": null,
                      "extendedPrice": null,
                      "extendedPriceFormatted": "",
                      "availability": null,
                      "rebateValue": null,
                      "urlProductImage": "/non-existing-image.png",
                      "urlProductSpecs": null,
                      "children": null,
                      "agreements": null,
                      "ancillaryChargesWithTitles": null,
                      "annuity": null,
                      "isSubLine": false,
                      "displayLineNumber": "1.1",
                      "licenseStartDate": null,
                      "licenseEndDate": null,
                      "contractStartDate": null,
                      "contractEndDate": null,
                      "serviceContractDetails": [],
                      "contractNo": null,
                      "contractType": null,
                      "license": null,
                      "status": "shipped",
                      "vendorStatus": null,
                      "customerPOLine": "000100",
                      "supplierQuoteRef": null,
                      "configID": null,
                      "locationID": null,
                      "serials": [
                        "MSNA005",
                        "MSNA001",
                        "MSNA004",
                        "MSNA000",
                        "MSNA002",
                        "MSNA003"            ],
                      "paKs": null,
                      "images": null,
                      "displayName": null          }
                  ],
                  "agreements": null,
                  "ancillaryChargesWithTitles": null,
                  "annuity": null,
                  "isSubLine": false,
                  "displayLineNumber": "1",
                  "licenseStartDate": null,
                  "licenseEndDate": null,
                  "contractStartDate": null,
                  "contractEndDate": null,
                  "serviceContractDetails": null,
                  "contractNo": null,
                  "contractType": null,
                  "license": randomStr(10, abc),
                  "status": "open",
                  "vendorStatus": null,
                  "customerPOLine": null,
                  "supplierQuoteRef": null,
                  "configID": null,
                  "locationID": null,
                  "serials": [],
                  "paKs": null,
                  "images": null
                },
                {
                  "id": "100",
                  "parent": null,
                  "vendorPartNo": "CON-SNT-C92048PE",
                  "manufacturer": "CISCO",
                  "displayName": null,
                  "quantity": 9,
                  "unitPrice": 0.0,
                  "unitPriceFormatted": "0.00",
                  "totalPrice": 0.0,
                  "totalPriceFormatted": "0.00",
                  "msrp": null,
                  "invoice": null,
                  "invoices": [
                    {
                      "id": "8035189627",
                      "line": "2",
                      "quantity": 3,
                      "price": 16.35,
                      "created": "11-18-2021"
                    }
                  ],
                  "trackings": [
                    {
                      "orderNumber": "6030684674",
                      "invoiceNumber": null,
                      "id": null,
                      "carrier": "FEDEX",
                      "serviceLevel": "FEDEX GROUND",
                      "trackingNumber": "486197188378",
                      "trackingLink": "http://www.fedex.com/Tracking?&cntry_code=us&language=english&tracknumbers=486197188378",
                      "type": "W0",
                      "description1": "FEDX GRND",
                      "date": "07-13-2021",
                      "dNote": "7038811481",
                      "dNoteLineNumber": "30",
                      "goodsReceiptNo": null
                    },
                    {
                      "orderNumber": "6030684674",
                      "invoiceNumber": null,
                      "id": null,
                      "carrier": "FEDEX",
                      "serviceLevel": "FEDEX GROUND",
                      "trackingNumber": "486197188378",
                      "trackingLink": "http://www.fedex.com/Tracking?&cntry_code=us&language=english&tracknumbers=486197188378",
                      "type": "W0",
                      "displayName": "FEDX GRND",
                      "date": "07-13-2021",
                      "dNote": "7038811481",
                      "dNoteLineNumber": "10",
                      "goodsReceiptNo": null
                    }
                  ],
                  "discounts": null,
                  "contract": null,
                  "displayName": "Cisco Smart Net Total Care - extended service agreement",
                  "mfrNumber": "CON-SNT-C92048PE",
                  "tdNumber": "13530066",
                  "upcNumber": null,
                  "unitListPrice": null,
                  "unitListPriceFormatted": null,
                  "extendedPrice": null,
                  "extendedPriceFormatted": "",
                  "availability": null,
                  "rebateValue": null,
                  "urlProductImage": null,
                  "urlProductSpecs": null,
                  "children": [
                    {
                      "id": "101",
                      "parent": "100",
                      "vendorPartNo": null,
                      "manufacturer": "HP ENT",
                      "displayName": "HP DL360P GEN8 S-BUY E5-2620 BASE US SVR",
                      "quantity": 6,
                      "unitPrice": 8572.18,
                      "unitPriceFormatted": "8,572.18",
                      "totalPrice": 51433.08,
                      "totalPriceFormatted": "51,433.08",
                      "msrp": null,
                      "invoice": null,
                      "invoices": [
                        {
                          "id": "8035207610",
                          "line": "2",
                          "quantity": 6,
                          "price": 51433.08,
                          "created": "07-16-2021"              }
                      ],
                      "trackings": [
                        {
                          "orderNumber": null,
                          "invoiceNumber": null,
                          "id": null,
                          "carrier": "CAMPBELL'S EXPRESS",
                          "serviceLevel": "LTL",
                          "trackingNumber": "7038809671",
                          "trackingLink": "http://expo.expeditors.com/expo/SQGuest?SearchType=shipmentSearch&TrackingNumber=7038809671",
                          "type": "JV",
                          "displayName": "CAMPBELLS EXPESS",
                          "date": "10-06-2021",
                          "dNote": "7038809671",
                          "dNoteLineNumber": "20",
                          "goodsReceiptNo": null              }
                      ],
                      "discounts": null,
                      "contract": null,
                      "displayName": null,
                      "mfrNumber": "670633-S01",
                      "tdNumber": "10214041",
                      "upcNumber": null,
                      "unitListPrice": null,
                      "unitListPriceFormatted": null,
                      "extendedPrice": null,
                      "extendedPriceFormatted": "",
                      "availability": null,
                      "rebateValue": null,
                      "urlProductImage": "/non-existing-image.png",
                      "urlProductSpecs": null,
                      "children": null,
                      "agreements": null,
                      "ancillaryChargesWithTitles": null,
                      "annuity": null,
                      "isSubLine": false,
                      "displayLineNumber": "1.1",
                      "licenseStartDate": null,
                      "licenseEndDate": null,
                      "contractStartDate": null,
                      "contractEndDate": null,
                      "serviceContractDetails": [],
                      "contractNo": null,
                      "contractType": null,
                      "license": null,
                      "status": "shipped",
                      "vendorStatus": null,
                      "customerPOLine": "000100",
                      "supplierQuoteRef": null,
                      "configID": null,
                      "locationID": null,
                      "serials": [
                        "MSNA005",
                        "MSNA001",
                        "MSNA004",
                        "MSNA000",
                        "MSNA002",
                      "MSNA003"           ],
                      "paKs": null,
                      "images": null,
                      "displayName": null          }
                  ],
                  "agreements": null,
                  "ancillaryChargesWithTitles": null,
                  "annuity": null,
                  "isSubLine": false,
                  "displayLineNumber": "2",
                  "licenseStartDate": null,
                  "licenseEndDate": null,
                  "contractStartDate": null,
                  "contractEndDate": null,
                  "serviceContractDetails": null,
                  "contractNo": 'QEY-V8E-PP',
                  "contractType": null,
                  "license": null,
                  "status": "cancelled",
                  "vendorStatus": null,
                  "customerPOLine": null,
                  "supplierQuoteRef": null,
                  "configID": null,
                  "locationID": null,
                  "serials": [],
                  "paKs": null,
                  "images": null
                },
                {
                  "id": "100",
                  "parent": null,
                  "vendorPartNo": "PWR-C5-BLANK",
                  "manufacturer": "CISCO",
                  "description1": null,
                  "quantity": 9,
                  "unitPrice": 0.0,
                  "unitPriceFormatted": "0.00",
                  "totalPrice": 0.0,
                  "totalPriceFormatted": "0.00",
                  "msrp": null,
                  "invoice": null,
                  "invoices": [
                    {
                      "id": "8035189627",
                      "line": "2",
                      "quantity": 3,
                      "price": 16.35,
                      "created": "11-18-2021"
                    }
                  ],
                  "trackings": [],
                  "discounts": null,
                  "contract": null,
                  "displayName": null,
                  "mfrNumber": "PWR-C5-BLANK",
                  "tdNumber": "14120862",
                  "upcNumber": null,
                  "unitListPrice": null,
                  "unitListPriceFormatted": null,
                  "extendedPrice": null,
                  "extendedPriceFormatted": "",
                  "availability": null,
                  "rebateValue": null,
                  "urlProductImage": null,
                  "urlProductSpecs": null,
                  "children": [
                    {
                      "id": "101",
                      "parent": "100",
                      "vendorPartNo": null,
                      "manufacturer": "HP ENT",
                      "description1": "HP DL360P GEN8 S-BUY E5-2620 BASE US SVR",
                      "quantity": 6,
                      "unitPrice": 8572.18,
                      "unitPriceFormatted": "8,572.18",
                      "totalPrice": 51433.08,
                      "totalPriceFormatted": "51,433.08",
                      "msrp": null,
                      "invoice": null,
                      "invoices": [
                        {
                          "id": "8035207610",
                          "line": "2",
                          "quantity": 6,
                          "price": 51433.08,
                          "created": "07-16-2021"              }
                      ],
                      "trackings": [
                        {
                          "orderNumber": "6030684674",
                          "invoiceNumber": null,
                          "id": null,
                          "carrier": "FEDEX",
                          "serviceLevel": "FEDEX GROUND",
                          "trackingNumber": "486197188378",
                          "trackingLink": "http://www.fedex.com/Tracking?&cntry_code=us&language=english&tracknumbers=486197188378",
                          "type": "W0",
                          "description1": "FEDX GRND",
                          "date": "07-13-2021",
                          "dNote": "7038811481",
                          "dNoteLineNumber": "30",
                          "goodsReceiptNo": null
                        },
                        {
                          "orderNumber": "6030684674",
                          "invoiceNumber": null,
                          "id": null,
                          "carrier": "FEDEX",
                          "serviceLevel": "FEDEX GROUND",
                          "trackingNumber": "486197188378",
                          "trackingLink": "http://www.fedex.com/Tracking?&cntry_code=us&language=english&tracknumbers=486197188378",
                          "type": "W0",
                          "description1": "FEDX GRND",
                          "date": "07-13-2021",
                          "dNote": "7038811481",
                          "dNoteLineNumber": "10",
                          "goodsReceiptNo": null
                        }
                      ],
                      "discounts": null,
                      "contract": null,
                      "displayName": null,
                      "mfrNumber": "670633-S01",
                      "tdNumber": "10214041",
                      "upcNumber": null,
                      "unitListPrice": null,
                      "unitListPriceFormatted": null,
                      "extendedPrice": null,
                      "extendedPriceFormatted": "",
                      "availability": null,
                      "rebateValue": null,
                      "urlProductImage": null,
                      "urlProductSpecs": null,
                      "children": null,
                      "agreements": null,
                      "ancillaryChargesWithTitles": null,
                      "annuity": null,
                      "isSubLine": false,
                      "displayLineNumber": "1.1",
                      "licenseStartDate": null,
                      "licenseEndDate": null,
                      "contractStartDate": null,
                      "contractEndDate": null,
                      "serviceContractDetails": [],
                      "contracNo1": null,
                      "contractType": null,
                      "license": null,
                      "status": "shipped",
                      "vendorStatus": null,
                      "customerPOLine": "000100",
                      "supplierQuoteRef": null,
                      "configID": null,
                      "locationID": null,
                      "serials": [
                        "MSNA005",
                        "MSNA001",
                        "MSNA004",
                        "MSNA000",
                        "MSNA002",
                        "MSNA003"            ],
                      "paKs": null,
                      "images": null,
                      "displayName": null          }
                  ],
                  "agreements": null,
                  "ancillaryChargesWithTitles": null,
                  "annuity": null,
                  "isSubLine": false,
                  "displayLineNumber": "3",
                  "licenseStartDate": null,
                  "licenseEndDate": null,
                  "contractStartDate": null,
                  "contractEndDate": null,
                  "serviceContractDetails": null,
                  "contractNo": null,
                  "contractType": null,
                  "license": randomStr(10, abc),
                  "status": "inProcess",
                  "vendorStatus": null,
                  "customerPOLine": null,
                  "supplierQuoteRef": null,
                  "configID": null,
                  "locationID": null,
                  "serials": [],
                  "paKs": null,
                  "images": null
                },
                {
                  "id": "100",
                  "parent": null,
                  "vendorPartNo": "C9200-NW-E-48",
                  "manufacturer": "CISCO",
                  "description1": null,
                  "quantity": 9,
                  "unitPrice": 0.0,
                  "unitPriceFormatted": "0.00",
                  "totalPrice": 0.0,
                  "totalPriceFormatted": "0.00",
                  "msrp": null,
                  "invoice": null,
                  "invoices": [
                    {
                      "id": "8035189627",
                      "line": "1",
                      "quantity": 3,
                      "price": 38.19,
                      "created": "11-18-2021"
                    }
                  ],
                  "trackings": [],
                  "discounts": null,
                  "contract": null,
                  "displayName": "Cisco Network Essentials - license - 48 ports",
                  "mfrNumber": "C9200-NW-E-48",
                  "tdNumber": "14173631",
                  "upcNumber": null,
                  "unitListPrice": null,
                  "unitListPriceFormatted": null,
                  "extendedPrice": null,
                  "extendedPriceFormatted": "",
                  "availability": null,
                  "rebateValue": null,
                  "urlProductImage": "/non-existing-image.png",
                  "urlProductSpecs": null,
                  "children": [],
                  "agreements": null,
                  "ancillaryChargesWithTitles": null,
                  "annuity": null,
                  "isSubLine": false,
                  "displayLineNumber": "4",
                  "licenseStartDate": null,
                  "licenseEndDate": null,
                  "contractStartDate": null,
                  "contractEndDate": null,
                  "serviceContractDetails": null,
                  "contractNo": 'ACDF ARKASLD',
                  "contractType": null,
                  "license": null,
                  "status": "inProcess",
                  "vendorStatus": null,
                  "customerPOLine": null,
                  "supplierQuoteRef": null,
                  "configID": null,
                  "locationID": null,
                  "serials": [],
                  "paKs": null,
                  "images": null
                }
              ],
              "orderNumber": "I008137569",
              "poNumber": "JoseDemoOctober_quote1",
              "endUserPO": "CCWR0007_8:35AM",
              "poDate": "",
              "blindPackaging": false,
              "shipComplete": false,
              "canBeExpedited": false,
              "status": "inProcess"
            },
            "error": { "code": 0, "messages": [], "isError": false }
          }
    },
};
