module.exports = {
    getRandomDate: function () {
        let [month, date, year] = new Date()
            .toLocaleDateString("en-US")
            .split("/");
        let dayFactor = Math.floor(Math.random() * 7);
        let deltaFactor = Math.floor(Math.random() * 2) ? 1 : -1;
        let randomDate = parseInt(date) + dayFactor * deltaFactor;
        console.log(month, date, year, dayFactor, deltaFactor, randomDate);
        return new Date(year, month, randomDate).toISOString();
    },
    getRandomArrayWithIds: (maxLength) => {
        const arrayLength = Math.floor(Math.random() * (maxLength + 1));
        let ids = [];
        const itemDefinition = {
            id: "123456789",
            version: "1",
            vendorId: "2323232",
            selectionFlag: "flag",
        };
        for (let i = 0; i < arrayLength; i++) {
            ids.push(itemDefinition);
        }
        return ids;
    },
    getRandomValues(range) {
        return String(1.0 * Math.floor(Math.random() * (range + 1)));
    },
    getRandomNumber(maxValue) {
        return Math.floor(Math.random() * maxValue + 1);
    },
    getQuoteDetailsResponse() {
        return {
            "content": {
                "details": {
                    "shipTo": {
                        "id": null,
                        "companyName": "TECH DATA CORPORATION",
                        "name": null,
                        "line1": "5350 Tech Data Dr",
                        "line2": null,
                        "line3": null,
                        "city": "Clearwater",
                        "state": "FL",
                        "zip": null,
                        "postalCode": "33760",
                        "country": "US",
                        "email": null,
                        "phoneNumber": null
                    },
                    "endUser": {
                        "id": null,
                        "companyName": "PEIGENESISCOM123",
                        "name": "Daniel  Vogt",
                        "line1": "2180 HORNIG RD",
                        "line2": null,
                        "line3": null,
                        "city": "PHILADELPHIA",
                        "state": "PA",
                        "zip": null,
                        "postalCode": "19116",
                        "country": "US",
                        "email": "Daniel.Vogt@techdata.com",
                        "phoneNumber": "0000"
                    },
                    "reseller": {
                        "id": null,
                        "companyName": "TECH DATA CORPORATION",
                        "name": "Daniel  Vogt",
                        "line1": "5350 Tech Data Dr",
                        "line2": " ",
                        "line3": null,
                        "city": "Clearwater",
                        "state": "FL",
                        "zip": null,
                        "postalCode": "33760",
                        "country": "US",
                        "email": "Daniel.Vogt@techdata.com",
                        "phoneNumber": "0000"
                    },
                    "source": [],
                    "notes": null,
                    "id": "121764062",
                    "orders": [{"id": null, "system": "Q", "salesOrg": "0100"}],
                    "customerPO": "21",
                    "endUserPO": null,
                    "poDate": null,
                    "quoteReference": "CCW QuoteId:4732840041",
                    "spaId": null,
                    "currency": "USD",
                    "currencySymbol": "$",
                    "subTotal": 19011.5500000,
                    "subTotalFormatted": "19,011.55",
                    "tier": "Commercial",
                    "items": [{
                        "id": "1",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "SAN Bundle incl. Nexus 93180YC-FX&MDS 91",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000014247378",
                        "upcNumber": null,
                        "unitListPrice": "0.0",
                        "unitListPriceFormatted": "0.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "2",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "MDS 9132T 32G 1 RU FC SWCH 8 ACTIVE FC",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000012996740",
                        "upcNumber": null,
                        "unitListPrice": "5820.3000000",
                        "unitListPriceFormatted": "5,820.30",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "3",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "SNTC-8X5XNBD MDS 9132T 32G 1 RU FC SWCH",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000012996739",
                        "upcNumber": null,
                        "unitListPrice": "225.0000000",
                        "unitListPriceFormatted": "225.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "4",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "650W AC PSU PT SIDE EXHAUST",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000013387287",
                        "upcNumber": null,
                        "unitListPrice": "827.8900000",
                        "unitListPriceFormatted": "827.89",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "5",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "MDS 9132 FAN TRAY PT SIDE EXHAUST",
                        "quantity": 2,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000013366560",
                        "upcNumber": null,
                        "unitListPrice": "200.7000000",
                        "unitListPriceFormatted": "200.70",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "6",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "650W AC PSU PT SIDE EXHAUST",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000013387287",
                        "upcNumber": null,
                        "unitListPrice": "827.8900000",
                        "unitListPriceFormatted": "827.89",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "7",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "16GBPS FC S/W SFP+ LC",
                        "quantity": 8,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000011262480",
                        "upcNumber": null,
                        "unitListPrice": "333.1600000",
                        "unitListPriceFormatted": "333.16",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "8",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "CTO PWR CORD 125VAC 13A NEMA 5-15 PLUG N",
                        "quantity": 2,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000010117017",
                        "upcNumber": null,
                        "unitListPrice": "0.0",
                        "unitListPriceFormatted": "0.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "9",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "MDS 9132 FAN TRAY PT SIDE EXHAUST",
                        "quantity": 2,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000013366560",
                        "upcNumber": null,
                        "unitListPrice": "200.7000000",
                        "unitListPriceFormatted": "200.70",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "10",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "MDS 9132T Accessory Kit for Cisco",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000014116891",
                        "upcNumber": null,
                        "unitListPrice": "0.0",
                        "unitListPriceFormatted": "0.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "11",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "Filler card for Blank Expansion Module S",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000014116888",
                        "upcNumber": null,
                        "unitListPrice": "0.0",
                        "unitListPriceFormatted": "0.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "12",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "NEXUS 9300 48P 10/25G SFP+ 6P 100G QSFP",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000012660188",
                        "upcNumber": null,
                        "unitListPrice": "27596.2500000",
                        "unitListPriceFormatted": "27,596.25",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "13",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "SNTC-8X5XNBD NEXUS 9300 W/ 48P",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000012705704",
                        "upcNumber": null,
                        "unitListPrice": "1318.8600000",
                        "unitListPriceFormatted": "1,318.86",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "14",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "Dummy PID for mode selection",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000014118038",
                        "upcNumber": null,
                        "unitListPrice": "0.0",
                        "unitListPriceFormatted": "0.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "15",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "ACI STOR S/W LIC",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000013366143",
                        "upcNumber": null,
                        "unitListPrice": "18063.0000000",
                        "unitListPriceFormatted": "18,063.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "16",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "SWSS UPG ACI STOR S/W LIC",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000013366142",
                        "upcNumber": null,
                        "unitListPrice": "366.0000000",
                        "unitListPriceFormatted": "366.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "17",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "OPT OUT PID FOR ACI ADV Subscription USE",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000014118988",
                        "upcNumber": null,
                        "unitListPrice": "0.0",
                        "unitListPriceFormatted": "0.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "18",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "Nexus 3K/9K Fixed Accessory Kit, 1RU fr",
                        "quantity": 1,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000013753097",
                        "upcNumber": null,
                        "unitListPrice": "0.0",
                        "unitListPriceFormatted": "0.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "19",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "Nexus NEBs AC 500W PSU - Port Side Inta",
                        "quantity": 2,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000014119303",
                        "upcNumber": null,
                        "unitListPrice": "0.0",
                        "unitListPriceFormatted": "0.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "20",
                        "parent": null,
                        "vendorPartNo": null,
                        "manufacturer": null,
                        "description": "CTO PWR CORD 125VAC 13A NEMA 5-15 PLUG N",
                        "quantity": 2,
                        "unitPrice": 0.0,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 0.0,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": null,
                        "tdNumber": "000000000010117017",
                        "upcNumber": null,
                        "unitListPrice": "0.0",
                        "unitListPriceFormatted": "0.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }]
                }
            }, "error": {"code": 0, "messages": [], "isError": false}
        };
    },
    getOrderDetailsResponse() {
        const  getRandomNumber = (maxValue) => {
            return Math.floor(Math.random() * maxValue + 1);
        };
        const randomDate = (start, end) => {
            return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
        }

        return {
            "content": {
                "id": "121764062",
                "details":null,
                "status" : "credit review",
                "shipTo": {
                    "id": null,
                    "companyName": null,
                    "name": "TECH DATA PRODUCT MANAGEMENT INC",
                    "line1": "13472 MARLAY AVENUE",
                    "line2": " ",
                    "line3": " ",
                    "city": "FONTANA",
                    "state": "CA",
                    "zip": "92337",
                    "postalCode": null,
                    "country": "US",
                    "email": null,
                    "contactEmail": null,
                    "phoneNumber": null
                },
                "endUser": [
                    {
                        "id": null,
                        "companyName": "COLINX",
                        "name": "Glenna Shelton",
                        "line1": "1536 GENESIS ROAD",
                        "line2": "",
                        "line3": "",
                        "city": "CROSSVILLE",
                        "state": "TN",
                        "zip": "38555",
                        "postalCode": "38555",
                        "country": "US",
                        "email": null,
                        "contactEmail": "gshelto@techdata.com",
                        "phoneNumber": "727-539-7429"
                    }
                ],
                "paymentDetails": {
                    "netValue": "0.00",
                    "reference": "XML6202113451",
                    "currency": "USD",
                    "currencySymbol": "$",
                    "paymentTermText": "1.50 % 10 Net 30",
                    "subtotal": 1.00,
                    "tax": 2000000.00,
                    "freight": 0,
                    "otherFees": 4.00,
                    "total": 5.00
                },
                "customer": "VERIZON",
                "orderPlacedDate" : "2021/03/04",
                "purchaseOrder" : "DP2020CureFor",
                "currencySymbol" : "$",
                "currency" : "USD",
                "items": [
                    {
                        "id": "1",
                        "parent": "0",
                        "vendorPartNo": null,
                        "manufacturer": '1224',
                        "description": "PLTNM TAB PRTNR STOCK $5+ MRC ACTIVATION",
                        "quantity": 5,
                        "unitPrice": 1548.22,
                        "status": "shipped",
                        "serial": [getRandomNumber(1000000), getRandomNumber(1000000)],
                        "shipDate": randomDate(new Date(2021, 0, 1), new Date()),
                        "unitPriceFormatted": "50.00",
                        "totalPrice": 1548.22,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "mfrNumber": '123',
                        "tdNumber": "000000000014118988",
                        "upcNumber": null,
                        "unitListPrice": null,
                        "unitListPriceFormatted": null,
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": null,
                        "ancillaryChargesWithTitles": null,
                        "annuity": null,
                        "isSubLine": false,
                        "displayLineNumber": "10"
                    },
                    {
                        "id": "2",
                        "parent": null,
                        "vendorPartNo": null,
                        "mfrNumber": '123',
                        "description": "MDS 9132T 32G 1 RU FC SWCH 8 ACTIVE FC",
                        "quantity": 1,
                        "unitPrice": 5160.00,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 5160.00,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "status": "onHold",
                        "serial": [],
                        "shipDate": randomDate(new Date(2021, 0, 1), new Date()),
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "tdNumber": "000000000012996740",
                        "upcNumber": null,
                        "unitListPrice": "5820.3000000",
                        "unitListPriceFormatted": "5,820.30",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, 
                    {
                        "id": "3",
                        "parent": null,
                        "vendorPartNo": null,
                        "mfrNumber": '123',
                        "description": "SNTC-8X5XNBD MDS 9132T 32G 1 RU FC SWCH",
                        "quantity": 1,
                        "unitPrice": 7672.99,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 7672.99,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "status": "cancelled",
                        "serial": [getRandomNumber(1000000), getRandomNumber(1000000), getRandomNumber(1000000)],
                        "shipDate": randomDate(new Date(2021, 0, 1), new Date()),
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "tdNumber": "000000000012996739",
                        "upcNumber": null,
                        "unitListPrice": "225.0000000",
                        "unitListPriceFormatted": "225.00",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "4",
                        "parent": null,
                        "vendorPartNo": null,
                        "mfrNumber": '123',
                        "description": "650W AC PSU PT SIDE EXHAUST",
                        "quantity": 1,
                        "unitPrice": 1548.22,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 1548.22,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "status": "shipped",
                        "serial": [getRandomNumber(1000000)],
                        "shipDate": randomDate(new Date(2021, 0, 1), new Date()),
                        "tdNumber": "000000000013387287",
                        "upcNumber": null,
                        "unitListPrice": "827.8900000",
                        "unitListPriceFormatted": "827.89",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "5",
                        "parent": null,
                        "vendorPartNo": null,
                        "mfrNumber": '123',
                        "description": "MDS 9132 FAN TRAY PT SIDE EXHAUST",
                        "quantity": 2,
                        "unitPrice": 9999.43,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 2168.92,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "status": "shipped",
                        "serial": [getRandomNumber(1000000), getRandomNumber(1000000)],
                        "shipDate": randomDate(new Date(2021, 0, 1), new Date()),
                        "tdNumber": "000000000013366560",
                        "upcNumber": null,
                        "unitListPrice": "200.7000000",
                        "unitListPriceFormatted": "200.70",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "6",
                        "parent": null,
                        "vendorPartNo": null,
                        "mfrNumber": '123',
                        "description": "650W AC PSU PT SIDE EXHAUST",
                        "quantity": 1,
                        "unitPrice": 8828.05,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 9210.99,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "status": "shipped",
                        "serial": [getRandomNumber(1000000)],
                        "shipDate": randomDate(new Date(2021, 0, 1), new Date()),
                        "tdNumber": "000000000013387287",
                        "upcNumber": null,
                        "unitListPrice": "827.8900000",
                        "unitListPriceFormatted": "827.89",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }, {
                        "id": "7",
                        "parent": null,
                        "vendorPartNo": null,
                        "mfrNumber": '123',
                        "description": "16GBPS FC S/W SFP+ LC",
                        "quantity": 8,
                        "unitPrice": 4028.12,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 7718.66,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "status": "open",
                        "serial": [getRandomNumber(1000000)],
                        "shipDate": randomDate(new Date(2021, 0, 1), new Date()),
                        "tdNumber": "000000000011262480",
                        "upcNumber": null,
                        "unitListPrice": "333.1600000",
                        "unitListPriceFormatted": "333.16",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    },
                    {
                        "id": "8",
                        "parent": null,
                        "vendorPartNo": null,
                        "mfrNumber": '123',
                        "description": "16GBPS FC S/W SFP+ LC",
                        "quantity": 8,
                        "unitPrice": 7888.66,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 7888.66,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "status": "inProcess",
                        "serial": [getRandomNumber(1000000)],
                        "shipDate": randomDate(new Date(2021, 0, 1), new Date()),
                        "tdNumber": "000000000011262480",
                        "upcNumber": null,
                        "unitListPrice": "333.1600000",
                        "unitListPriceFormatted": "333.16",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    },
                    {
                        "id": "9",
                        "parent": null,
                        "vendorPartNo": null,
                        "mfrNumber": '123',
                        "description": "16GBPS FC S/W SFP+ LC",
                        "quantity": 8,
                        "unitPrice": 4028.12,
                        "unitPriceFormatted": "0.00",
                        "totalPrice": 7718.66,
                        "totalPriceFormatted": "0.00",
                        "msrp": null,
                        "invoice": null,
                        "discounts": null,
                        "contract": null,
                        "shortDescription": null,
                        "status": "shipped",
                        "serial": [getRandomNumber(1000000)],
                        "shipDate": randomDate(new Date(2021, 0, 1), new Date()),
                        "tdNumber": "000000000011262480",
                        "upcNumber": null,
                        "unitListPrice": "333.1600000",
                        "unitListPriceFormatted": "333.16",
                        "extendedPrice": null,
                        "extendedPriceFormatted": "",
                        "availability": null,
                        "rebateValue": null,
                        "urlProductImage": null,
                        "urlProductSpecs": null,
                        "children": null,
                        "agreements": []
                    }
                ],
        },
            "error": { "code": 0, "messages": [], "isError": false }
        }
    },
};
