//2021 (c) Tech Data Corporation -. All Rights Reserved.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RenewalsService
{
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.Serialization;

    [ExcludeFromCodeCoverage]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RenewalSearchDto", Namespace="http://schemas.datacontract.org/2004/07/TechData.EC.Services.Order.DataContract.R" +
        "enewals")]
    public partial class RenewalSearchDto : object
    {
        
        private string CustomerNumberField;
        
        private string EndUserSearchStringField;
        
        private System.DateTime ExpirationSearchFromField;
        
        private System.DateTime ExpirationSearchToField;
        
        private string ProductField;
        
        private string QuoteNumberField;
        
        private string SalesOrganizationField;
        
        private string VendorNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerNumber
        {
            get
            {
                return this.CustomerNumberField;
            }
            set
            {
                this.CustomerNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndUserSearchString
        {
            get
            {
                return this.EndUserSearchStringField;
            }
            set
            {
                this.EndUserSearchStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationSearchFrom
        {
            get
            {
                return this.ExpirationSearchFromField;
            }
            set
            {
                this.ExpirationSearchFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationSearchTo
        {
            get
            {
                return this.ExpirationSearchToField;
            }
            set
            {
                this.ExpirationSearchToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuoteNumber
        {
            get
            {
                return this.QuoteNumberField;
            }
            set
            {
                this.QuoteNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesOrganization
        {
            get
            {
                return this.SalesOrganizationField;
            }
            set
            {
                this.SalesOrganizationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VendorName
        {
            get
            {
                return this.VendorNameField;
            }
            set
            {
                this.VendorNameField = value;
            }
        }
    }

    [ExcludeFromCodeCoverage]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RenewalDto", Namespace="http://schemas.datacontract.org/2004/07/TechData.EC.Services.Order.DataContract.R" +
        "enewals")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RenewalsService.RenewalDetailDto))]
    public partial class RenewalDto : object
    {
        
        private string CurrentProductDescriptionField;
        
        private string CurrentSKUField;
        
        private string CustomerNumberField;
        
        private string EndUserNameField;
        
        private System.DateTime ExpirationDateField;
        
        private long IdField;
        
        private string LicenseSerialNumberField;
        
        private decimal LineItemPriceField;
        
        private string OriginalPONumberField;
        
        private long QuoteIdField;
        
        private int QuoteQtyField;
        
        private decimal QuoteTotalField;
        
        private string RenewalProductDescriptionField;
        
        private string RenewalSKUField;
        
        private string ResultingOrderCertificateNumberField;
        
        private string ResultingOrderContractNumberField;
        
        private string ResultingOrderLicenseIdField;
        
        private string ResultingOrderRenewalIdField;
        
        private System.DateTime StartDateField;
        
        private string TDPartNumberField;
        
        private string VendorNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentProductDescription
        {
            get
            {
                return this.CurrentProductDescriptionField;
            }
            set
            {
                this.CurrentProductDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentSKU
        {
            get
            {
                return this.CurrentSKUField;
            }
            set
            {
                this.CurrentSKUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerNumber
        {
            get
            {
                return this.CustomerNumberField;
            }
            set
            {
                this.CustomerNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndUserName
        {
            get
            {
                return this.EndUserNameField;
            }
            set
            {
                this.EndUserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationDate
        {
            get
            {
                return this.ExpirationDateField;
            }
            set
            {
                this.ExpirationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicenseSerialNumber
        {
            get
            {
                return this.LicenseSerialNumberField;
            }
            set
            {
                this.LicenseSerialNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LineItemPrice
        {
            get
            {
                return this.LineItemPriceField;
            }
            set
            {
                this.LineItemPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalPONumber
        {
            get
            {
                return this.OriginalPONumberField;
            }
            set
            {
                this.OriginalPONumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long QuoteId
        {
            get
            {
                return this.QuoteIdField;
            }
            set
            {
                this.QuoteIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuoteQty
        {
            get
            {
                return this.QuoteQtyField;
            }
            set
            {
                this.QuoteQtyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal QuoteTotal
        {
            get
            {
                return this.QuoteTotalField;
            }
            set
            {
                this.QuoteTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RenewalProductDescription
        {
            get
            {
                return this.RenewalProductDescriptionField;
            }
            set
            {
                this.RenewalProductDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RenewalSKU
        {
            get
            {
                return this.RenewalSKUField;
            }
            set
            {
                this.RenewalSKUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultingOrderCertificateNumber
        {
            get
            {
                return this.ResultingOrderCertificateNumberField;
            }
            set
            {
                this.ResultingOrderCertificateNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultingOrderContractNumber
        {
            get
            {
                return this.ResultingOrderContractNumberField;
            }
            set
            {
                this.ResultingOrderContractNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultingOrderLicenseId
        {
            get
            {
                return this.ResultingOrderLicenseIdField;
            }
            set
            {
                this.ResultingOrderLicenseIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultingOrderRenewalId
        {
            get
            {
                return this.ResultingOrderRenewalIdField;
            }
            set
            {
                this.ResultingOrderRenewalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TDPartNumber
        {
            get
            {
                return this.TDPartNumberField;
            }
            set
            {
                this.TDPartNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VendorName
        {
            get
            {
                return this.VendorNameField;
            }
            set
            {
                this.VendorNameField = value;
            }
        }
    }

    [ExcludeFromCodeCoverage]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RenewalDetailDto", Namespace="http://schemas.datacontract.org/2004/07/TechData.EC.Services.Order.DataContract.R" +
        "enewals")]
    public partial class RenewalDetailDto : RenewalsService.RenewalDto
    {
        
        private string EndUserAddressField;
        
        private string EndUserCityField;
        
        private string EndUserContactEmailField;
        
        private string EndUserContactNameField;
        
        private string EndUserContactPhoneField;
        
        private string EndUserPostalCodeField;
        
        private string EndUserStateField;
        
        private string ProductHardwareSKUField;
        
        private string ProductHardwareSerialNumberField;
        
        private string ResellerContactEmailField;
        
        private string ResellerContactNameField;
        
        private string ResellerPONumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndUserAddress
        {
            get
            {
                return this.EndUserAddressField;
            }
            set
            {
                this.EndUserAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndUserCity
        {
            get
            {
                return this.EndUserCityField;
            }
            set
            {
                this.EndUserCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndUserContactEmail
        {
            get
            {
                return this.EndUserContactEmailField;
            }
            set
            {
                this.EndUserContactEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndUserContactName
        {
            get
            {
                return this.EndUserContactNameField;
            }
            set
            {
                this.EndUserContactNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndUserContactPhone
        {
            get
            {
                return this.EndUserContactPhoneField;
            }
            set
            {
                this.EndUserContactPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndUserPostalCode
        {
            get
            {
                return this.EndUserPostalCodeField;
            }
            set
            {
                this.EndUserPostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndUserState
        {
            get
            {
                return this.EndUserStateField;
            }
            set
            {
                this.EndUserStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductHardwareSKU
        {
            get
            {
                return this.ProductHardwareSKUField;
            }
            set
            {
                this.ProductHardwareSKUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductHardwareSerialNumber
        {
            get
            {
                return this.ProductHardwareSerialNumberField;
            }
            set
            {
                this.ProductHardwareSerialNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResellerContactEmail
        {
            get
            {
                return this.ResellerContactEmailField;
            }
            set
            {
                this.ResellerContactEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResellerContactName
        {
            get
            {
                return this.ResellerContactNameField;
            }
            set
            {
                this.ResellerContactNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResellerPONumber
        {
            get
            {
                return this.ResellerPONumberField;
            }
            set
            {
                this.ResellerPONumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RenewalsService.IRenewalsService")]
    public interface IRenewalsService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRenewalsService/RenewalSearch", ReplyAction="http://tempuri.org/IRenewalsService/RenewalSearchResponse")]
        System.Threading.Tasks.Task<RenewalsService.RenewalDto[]> RenewalSearchAsync(RenewalsService.RenewalSearchDto searchDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRenewalsService/GetRenewalDetails", ReplyAction="http://tempuri.org/IRenewalsService/GetRenewalDetailsResponse")]
        System.Threading.Tasks.Task<RenewalsService.RenewalDetailDto> GetRenewalDetailsAsync(string customerNumber, string salesOrganization, long renewalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRenewalsService/MarkAsRenewed", ReplyAction="http://tempuri.org/IRenewalsService/MarkAsRenewedResponse")]
        System.Threading.Tasks.Task<bool> MarkAsRenewedAsync(string customerNumber, long renewalId, System.DateTime renewedOnDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IRenewalsServiceChannel : RenewalsService.IRenewalsService, System.ServiceModel.IClientChannel
    {
    }

    [ExcludeFromCodeCoverage]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class RenewalsServiceClient : System.ServiceModel.ClientBase<RenewalsService.IRenewalsService>, RenewalsService.IRenewalsService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RenewalsServiceClient() : 
                base(RenewalsServiceClient.GetDefaultBinding(), RenewalsServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IRenewalsService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RenewalsServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(RenewalsServiceClient.GetBindingForEndpoint(endpointConfiguration), RenewalsServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RenewalsServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RenewalsServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RenewalsServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RenewalsServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RenewalsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<RenewalsService.RenewalDto[]> RenewalSearchAsync(RenewalsService.RenewalSearchDto searchDto)
        {
            return base.Channel.RenewalSearchAsync(searchDto);
        }
        
        public System.Threading.Tasks.Task<RenewalsService.RenewalDetailDto> GetRenewalDetailsAsync(string customerNumber, string salesOrganization, long renewalId)
        {
            return base.Channel.GetRenewalDetailsAsync(customerNumber, salesOrganization, renewalId);
        }
        
        public System.Threading.Tasks.Task<bool> MarkAsRenewedAsync(string customerNumber, long renewalId, System.DateTime renewedOnDate)
        {
            return base.Channel.MarkAsRenewedAsync(customerNumber, renewalId, renewedOnDate);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRenewalsService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRenewalsService))
            {
                return new System.ServiceModel.EndpointAddress("http://usdevmtap04.us.tdworldwide.com/OrderService/RenewalsService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RenewalsServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IRenewalsService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RenewalsServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IRenewalsService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IRenewalsService,
        }
    }
}
