resources:
  repositories:
    - repository: DCP
      type: git
      name: 'WW Digital Commerce/DigitalCommercePlatform'

trigger: none

schedules:
- cron: "15 0 * * *"
  displayName: 'Daily night build'
  branches:
    include:
    - develop

pool:
  name: 'DC-Buildpool-Windows'
  workspace:
    clean: all

extends:
  template: pullrequest-template-v3.yml@DCP
  parameters:
          projectSources: 'services/Commerce/DigitalCommercePlatform.UIServices.Commerce.sln'
          unitTestSources: 'services/Commerce/DigitalCommercePlatform.UIServices.Commerce.*/*Tests.csproj'
          projectKey: 'DC-DF-Commerce-UI'
          projectName: 'DC-DF-Commerce-UI'          